register(GRAMPLET,
         id="WikiTree Gramplet", 
         name=_("WikiTree Gramplet"),
         description = _("a program that says 'Hello World'"),
         status = STABLE,
         version="0.0.1",
         fname="WikiTree.py",
         height = 20,
         gramplet = 'WikiTreeGramplet',
         gramplet_title=_("WikiTree Gramplet"),
         gramps_target_version="5.0",
         help_url="WikiTree Gramplet",
         navtypes=["Person"],
         )
